# -*- coding: utf-8 -*-
"""Projekt zaliczeniowy .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1479Fn1xvpFAaU9q72zDtZYS58VFx3h_B
"""

import random

def nazwybor(wybor):
    return ['KAMIEŃ', 'PAPIER', 'NOŻYCE'][wybor-1]
def zwyciezca(uzytkownik, komputer):
    if uzytkownik == komputer:
        return "REMIS"
    elif (uzytkownik - komputer) % 3 == 1:
        return "UŻYTKOWNIK"
    else:
        return "KOMPUTER"
while True:
    graj = input("Czy chcesz zagrać w KAMIEŃ PAPIER NOŻYCE? \n (T/N): ").lower()
    if graj == 'n':
        break
    elif graj != 't':
        print("BŁĄD WPISZ T LUB N")
        continue

    try:
        uzytkownik = int(input("WYBIERZ \n1=KAMIEŃ\n2=PAPIER\n3=NOŻYCE\n "))
        if uzytkownik not in [1, 2, 3]:
            raise ValueError("BŁĄD")
    except ValueError as e:
        print(e)
        continue
    nazwa_uzytkownika = nazwybor(uzytkownik)
    print(f'TWOJ WYBÓR TO : {nazwa_uzytkownika}')

    komputer = random.randint(1, 3)
    komputer = nazwybor(komputer)
    print(f"KOMPUTER WYBRAŁ: {nazwa_komputera}")

    wynik = zwyciezca(uzytkownik, wybor_komputera)
    print(f'{nazwa_uzytkownika} vs {nazwa_komputera} -> {"NO I MAMY REMIS !" if wynik == "REMIS" else wynik + " WYGRYWA"}')

    if input("GRAMY JESZCZE RAZ ??? (T/N): ").lower() == 'n':
        break

print("Dziękujemy za grę!")

