# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqM-5OrjzI0ILzSBdWMa6H5SlFAws5qw
"""

#1.Write a Python program to calculate the length of a string.
def string_length(strin):
    count = 0
    for char in strin:
     count += 1
    return count
print(string_length(input()))

#2.Get a single string from two given strings, separated by a space and swap the first two characters of each string
def chars_mix_up(a, b):
    new_a = b[:2] + a[2:]
    new_b = a[:2] + b[2:]
    return new_a + ' ' + new_b
print(chars_mix_up(input(), input()))

#3.Write a Python program to lowercase the first n characters in a string.
n = input()
print(n[:5].lower() + n[5:])

# 4. Write a Python program to reverse a string
def reverse_string(str1):
    return ''.join(reversed(str1))
print(reverse_string(input()))

#5.Write a Python program to reverse words in a string.
def reverse_string_words(text):
    for line in text.split('\n'):
        return(' '.join(line.split()[::-1]))
print(reverse_string_words(input()))

#6. Write a Python program to remove the n index character from a nonempty string.
def remove_char(str, n):
    first = str[:n]
    last = str[n+1:]
    return first + last
print(remove_char('MERITO', 0))
print(remove_char('MERITO', 3))
print(remove_char('MERITO', 5))

