# -*- coding: utf-8 -*-
"""Conditional Statements and loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2BlBFfX8-NgZSkjfeE6gAN_8hft07kf
"""

#1.Write a Python program to find those numbers which are divisible by 7 and multiples of 5, between 1500 and 2700 (both included).
result = []
for num in range(1500, 2701):
    if num % 7 == 0 and num % 5 == 0:
        result.append(num)
print("Liczby podzielne przez 7 i wielokrotnością 5 między 1500 a 2700 ")
print(result)

#2.Write a Python program to convert temperatures to and from Celsius and Fahrenheit.
def celsius_do_fahrenheita(celsius):
    return (celsius * 9/5) + 32
def fahrenheit_do_celsius(fahrenheit):
    return (fahrenheit - 32) * 5/9
celsius = float(input("Podaj temperaturę w stopniach Celsjusza: "))
fahrenheit = celsius_do_fahrenheita(celsius)
print(f"{celsius} stopni Celsjusza to {fahrenheit:.2f} stopni Fahrenheita.")

fahrenheit = float(input("Podaj temperaturę w stopniach Fahrenheita: "))
celsiu = fahrenheit_do_celsius(fahrenheit)
print(f"{fahrenheit} stopni Fahrenheita to {celsius:.2f} stopni Celsjusza.")

#3.Write a Python program to construct the following pattern, using a nested for loop.
max_stars =5
for i in range(max_stars + 1):
    for j in range(i):
        print("*", end=" ")
    print()
for i in range(max_stars - 1, 0, -1):
    for j in range(i):
        print("*", end=" ")
    print()

#4.Write a Python program that accepts a word from the user and reverses it.
word = input("Napisz tekst ")
reversed_word = word[::-1]
print("Odwrocony tekst:", reversed_word)

#5.Write a Python program that prints all the numbers from 0 to 6 except 3 and 6.
for num in range(7):
    if num == 3 or num == 6:
        continue
    print(num)

#6.Write a Python program to get the Fibonacci series between 0 and 50.
a, b = 0, 1
print(a)
while b < 50:
    print(b)
    a, b = b, a + b

#7.Write a Python program that prints each item and its corresponding type from the following list.
my_list = [1, "Piesek", 3.14, True, [1, 2, 3], (4, 5), {"a": 1, "b": 2}]
for item in my_list:
    print(f" {item}, to {type(item)}")

#8.Write a Python program that iterates the integers from 1 to 50. For multiples of three print "Fizz"
# instead of the number and for multiples of five print "Buzz". For numbers that are multiples of three and five, print "FizzBuzz"
for num in range(1, 51):
    if num % 3 == 0 and num % 5 == 0:
        print("FizzBuzz")
    elif num % 3 == 0:
        print("Fizz")
    elif num % 5 == 0:
        print("Buzz")
    else:
        print(num)

#9.Write a Python program to print the alphabet pattern 'A'.
def print_A(height):
    width = height * 2 - 1

    for row in range(height):
        for col in range(width):
            if (row == 0 and col % 2 != 0) or (row == height // 2) or (col == 0 and row != 0 and row != height // 2) or (col == width - 1 and row != 0 and row != height // 2):
                print("*", end="")
            else:
                print(" ", end="")
        print()
print_A(7)

#10.Write a Python program to print the alphabet pattern 'L'.
def print_L(height):
    width = height
    for row in range(height):
        for col in range(width):
            if col == 0 or row == height - 1:
                print("*", end="")
            else:
                print(" ", end="")
        print()
print_L(7)

#11.Write a Python program to print the alphabet pattern 'O'.
def print_O(size):
    for row in range(size):
        for col in range(size):
            if (row == 0 or row == size - 1) and (col > 0 and col < size - 1):
                print("*", end="")
            elif (col == 0 or col == size - 1) and (row > 0 and row < size - 1):
                print("*", end="")
            else:
                print(" ", end="")
        print()

print_O(7)

#12.Write a Python program to print the alphabet pattern 'R'.
def print_R(height):
    width = height

    for row in range(height):
        for col in range(width):
            if col == 0 or (row == 0 or row == height // 2) and col < width - 1 or (col == width - 1 and row != 0 and row != height // 2):
                print("*", end="")
            else:
                print(" ", end="")
        print()
print_R(7)

#13.Write a Python program to print the alphabet pattern 'Z'.
def print_Z(height):
    width = height

    for row in range(height):
        for col in range(width):
            if row == 0 or row == height - 1 or row + col == height - 1:
                print("*", end="")
            else:
                print(" ", end="")
        print()
print_Z(7)

#14.Write a Python program to print the alphabet pattern 'X'.
def print_X(size):
    for i in range(size):
        for j in range(size):
            if i == j or i + j == size - 1:
                print("*", end="")
            else:
                print(" ", end="")
        print()
print_X(7)

#15.Write a Python program to print the alphabet pattern 'U'.
def print_U(height):
    width = height + 2

    for row in range(height):
        for col in range(width):
            if (col == 0 or col == width - 1) and row != height - 1 or row == height - 1 and (col > 0 and col < width - 1):
                print("*", end="")
            else:
                print(" ", end="")
        print()
print_U(7)

#16.Write a Python program to print the alphabet pattern 'T'.
def print_T(height):
    width = height

    for row in range(height):
        for col in range(width):
            if row == 0 or col == height // 2:
                print("*", end="")
            else:
                print(" ", end="")
        print()
print_T(7)

#17.Write a Python program to calculate a dog's age in dog years.
def calculate(human_years):
    if human_years <= 2:
        dog_years = human_years * 10.5
    else:
        dog_years = 2 * 10.5 + (human_years - 2) * 4
    return dog_years
human_age = float(input("Podaj wiek psa w latach ludzkich: "))
dog_age = calculate(human_age)
print("Wiek psa w psich latach to:", dog_age)

#18.Write a Python program to check whether an alphabet is a vowel or consonant.
letter = input("Podaj litere ").lower()
if letter in ['a', 'e', 'i', 'o', 'u']:
    print(f"{letter} jest samogłoską")
else:
    print(f"{letter} nie jest samogłoską")

#19.Write a Python program to sum two integers. However, if the sum is between 15 and 20 it will return 20.
def sum_within_range(a, b):
    result = a + b
    if 15 <= result <= 20:
        return 20
    else:
        return result
num1 = int(input("Podaj pierwszą liczbę całkowitą: "))
num2 = int(input("Podaj drugą liczbę całkowitą: "))

result = sum_within_range(num1, num2)
print("Wynik to:", result)

#20.Write a Python program that checks whether a string represents an integer or not.
def is_integer(s):
    try:
        int(s)
        return True
    except ValueError:
        return False
string1 = "12345"
string2 = "3.14321321321"
string3 = "-1321213"
string4 = "abc123dsa"

print(f"'{string1}'reprezentuje liczbę całkowitą:", is_integer(string1))
print(f"'{string2}'reprezentuje liczbę całkowitą:", is_integer(string2))
print(f"'{string3}'reprezentuje liczbę całkowitą:", is_integer(string3))
print(f"'{string4}' reprezentuje liczbę całkowitą::", is_integer(string4))