# -*- coding: utf-8 -*-
"""List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152VJkuTslxa4Y5rHFV-HCYGgcY1j3wFI
"""

#1.Write a Python program to sum all the items in a list.
def sum(items):
    total = 0
    for item in items:
        total += item
    return total
my_list = [1, 2, 3, 4, 5]
print("Suma listy:", sum(my_list))

#2.Write a Python program to multiply all the items in a list.
def multiply(items):
    result = 1
    for item in items:
        result *= item
    return result

my_list = [1, 2, 3, 4, 5]
print("mnozenie listy :", multiply(my_list))

#3.Write a Python program to remove duplicates from a list.
def duplikaty(input_list):
    unique_list = []
    for item in input_list:
        if item not in unique_list:
            unique_list.append(item)
    return unique_list

my_list = [1, 2, 3, 3, 4, 4, 2, 5]
result = duplikaty(my_list)
print("Lista po usunieciu duplikatow:", result)

#4.Write a Python program to check if a list is empty or not
def empty(input_list):
    if not input_list:
        return True
    else:
        return False
my_list = [4,5]
if empty(my_list):
    print("Lista pusta")
else:
    print("Lista nie jest pusta")

# 5.Write a Python function that takes two lists and returns True if they have at least one common member.
def common(list1, list2):
    for item in list1:
        if item in list2:
            return True
    return False

list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
print(common(list1, list2))

list3 = [5, 6, 7, 8, 9]
print(common(list1, list3))

#6.Write a Python program to get the largest number from a list.
def get_largest_number(numbers):
    if not numbers:
        return None
    largest_number = numbers[0]
    for number in numbers:
        if number > largest_number:
            largest_number = number
    return largest_number
my_list = [0, 105, 21, 8, 15]
largest_number = get_largest_number(my_list)
print("Największa liczba na liście to", largest_number)

#7.Write a Python program to get the smallest number from a list.
def get_smallest_number(numbers):
    if not numbers:
        return None
    smallest_number = numbers[0]
    for number in numbers:
        if number < smallest_number:
            smallest_number = number
    return smallest_number

my_list = [0, 105, 21, 8, 15]
smallest_number = get_smallest_number(my_list)
print("Najmniejsza liczba na liście to:", smallest_number)

#8.Write a Python program to clone or copy a list.
def clone_list(original_list):
    return original_list[:]
original_list = [1, 2, 3, 4, 5]
cloned_list = clone_list(original_list)
print("Oryginalna lista", original_list)
print("Sklonowana lista", cloned_list)

#9.Write a Python program to select an item randomly from a list.
import random

def select_random_item(input_list):
    random_item = random.choice(input_list)
    return random_item

my_list = [10, 21, 33, 422, 51]
random_item = select_random_item(my_list)
print("Losowy Element", random_item)

# 10.Write a Python program to get unique values from a list.
def unique(input_list):
    unique_values = set(input_list)
    return list(unique_values)

input_list = [1, 2, 2, 3, 4, 4, 5]
unique_values = unique(input_list)
print("unikalne wartosci to :", unique_values)

#11.Write a Python program to insert an element before each element of a list.
def insert_before_each(input_list, element):
    result = []
    for item in input_list:
        result.append(element)
        result.append(item)
    return result

lista = [2, 4, 6, 8]
element = 100
modified = insert_before_each(lista, element)
print("Zmodyfikowana lista:", modified)

#12.Write a Python program to print a list of space-separated elements.
def print_space_separated(input_list):
    result = ' '.join(map(str, input_list))
    print(result)

input_list = [1,2,3,4,5]
print_space_separated(input_list)

#13.Write a Python program to convert a list of characters into a string.
def list_to_string(char_list):
    result = ''.join(char_list)
    return result

char_list = ['C', 'Z', 'E', 'S', 'C']
result = list_to_string(char_list)
print(result)

#14.Write a Python program to get the frequency of elements in a list.
def elements(lst):
    freq_dict = {}
    for item in lst:
        if item in freq_dict:
            freq_dict[item] += 1
        else:
            freq_dict[item] = 1
    return freq_dict

my_list = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
frequency = elements(my_list)
for key, value in frequency.items():
    print(f"{key}: {value}")

#15.Write a Python program to find common items in two lists.
def items(list1, list2):
    common_items = []
    for item in list1:
        if item in list2 and item not in common_items:
            common_items.append(item)
    return common_items

list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]
common_items = items(list1, list2)
print("Wspólne elementy:", common_items)

#16.Write a Python program to split a list based on the first character of a word.
def split(word_list):
    result_dict = {}
    for word in word_list:
        first_char = word[0]
        result_dict.setdefault(first_char, []).append(word)
    return result_dict

word_list = ["jablko", "banan", "gruszka", "mango", "granat"]
split_result = split(word_list)
for key, value in split_result.items():
    print(f"Słowo zaczynjace sie na  '{key}': {value}")

#17.Write a Python program to print the numbers of a specified list after removing even numbers from it.
def print_numbers(numbers):
    # Remove even numbers from the list
    odd_numbers = [num for num in numbers if num % 2 != 0]

    # Print the remaining odd numbers
    for num in odd_numbers:
        print(num)

# Example usage:
number_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("lista po usunięciu z niej liczb parzystych.")
print_numbers(number_list)

#18.Write a Python program to access the index of a list.
def access_index_of_list(my_list):
    for index, value in enumerate(my_list):
        print(f"Indeks: {index}, wartosc: {value}")
word_list = ["jablko", "banan", "gruszka", "mango", "granat"]
access_index_of_list(word_list)

#19.Write a Python program to change the position of every n-th value to the (n+1)th in a list.
def position(input_list):
    for i in range(0, len(input_list) - 1, 2):
        input_list[i], input_list[i + 1] = input_list[i + 1], input_list[i]
    return input_list
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
changed_list = position(my_list)
print("Zmieniona lista:", changed_list)

#20.Write a Python program to count the number of elements in a list within a specified range.
def elements(input_list, start_range, end_range):
    count = 0
    for num in input_list:
        if start_range <= num <= end_range:
            count += 1
    return count
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
start_range = 3
end_range = 7
result = elements(my_list, start_range, end_range)
print("Liczba elementów w określonym zakresie", result)